### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by Iheve** [tonyguolei/projet_dac#11]
How to reproduce the problem:
* Create a project with title "Très beau test"
* List projects
* The 'è' character is not well displayed.

In the database, the 'è' character is not well displayed neither.

Java might not know that we are using UTF8

**Comment by tonyguolei** [comment]
It should use new String(request.getParameter("XXX").getBytes("iso-8859-1"), "UTF-8") instead of request.getParameter("XXX") to avoid problem of encoding

**Comment by tonyguolei** [comment]
I don't test the case when request.get parameter is null, new String (null) might cause problem. So I rereopen this issue

**Comment by Iheve** [comment]
@tonyguolei you showed made me on the track

**Comment by Iheve** [comment]
Could someone check that its working with a windows client (which should have a non-utf8 default encoding)
