### ISSUE TITLE
Project deletion

### ISSUE THREAD

**Issue by Minos** [tonyguolei/projet_dac#26]
Should it be possible to just delete a project? The only related user cases that I can think of are the following:

* User wants to cancel his project
* The project’s deadline has been reached and the funding wasn’t successful

which look more like a project cancellation, and would be best handled by a "cancelled" flag in the database for the first case, and by comparing the deadline with the current date for the second case.

**Comment by Iheve** [comment]
I think we agreed during conception on project deletion.
We can filter out project which have a long passed deadline.

**Comment by Minos** [comment]
fixed by 10fd851674ac4d0148841c6e98b2021fb732fb69

**Comment by Iheve** [comment]
10fd851674ac4d0148841c6e98b2021fb732fb69 duplicates the ability for the administrator to delete a project (administration tab).
You have to do project deletion by its owner

**Comment by Minos** [comment]
OK.  98d9f00bd93d1cdb9800929f1e7ddb5c36eb21f8 removes the duplicate button and introduces project deletion by its owner in the controller.
