### ISSUE TITLE
Use transaction to transfer fund to user

### ISSUE THREAD

**Issue by Jojolejobar** [tonyguolei/projet_dac#30]
Currently, we used two transaction to get the job done (in ejb/TaskScheduler)
```java
User user = p.getIdOwner();
user.addBalance(fundDao.getFundLevel(p));
userDao.update(user);
p.transferDone();
projectDao.update(p);
```

There is a problem if the server crash just after update the user, because the flag for project will not be set and so the user can get the money several time.

**Comment by tonyguolei** [comment]
I think you should use transaction in EJB. This is the example (Maybe the
code is not right):

UserTransaction utx = context.getUserTransaction();
 try { utx.begin();
      //Do something with the EntityManager such as persist(), merge() or
remove()
      /** * If any error happens before reaching commit, the rollback()
method
      * is waiting below at the catch{} clause, before hitting on the
commit() method. **/
      utx.commit();
} catch(Throwable t) {
      //Invokes only if the above throws and Exception or instance of
Throwable
      utx.rollback();
      throws new Exception(t.getMessage());
}

2015-01-08 18:17 GMT+01:00 Guillaume Perrin <notifications@github.com>:
