### ISSUE TITLE
The creation date doesn't display correctly

### ISSUE THREAD

**Issue by tonyguolei** [tonyguolei/projet_dac#39]
When I create a project, the creation date is "20 hours ago", instead of the actual time.

**Comment by Iheve** [comment]
I think this is because the display format trunk the date.

**Comment by posva** [comment]
Non. ça c'est parce que la base données est en GMT +0 au lieu de GMT +1 qui est l'heure actuelle. L'idéal serait de passer l'heure (et la date) correcte dans le code Java. Je n'qai aucune idée de comment ça se fait
