### ISSUE TITLE
Ajout de milième de $

### ISSUE THREAD

**Issue by posva** [tonyguolei/projet_dac#40]
On peut fund avec des milièmes de $. Les valeurs devraient être coupées aux centièmes.

Reproduction du bug:

* Aller sur un projet
* Fund avec `1.009`
* Fund à nouveaux avec `1.009`
* Le project a augmenté de `1.01` au lieu de `1`

** Attention ce bug ne marche pas si l'on met `0.005` car l'insert de 0 n'a pas l'air d'être pris en compte **

**Comment by Iheve** [comment]
Not reproductible
