### ISSUE TITLE
Elements growing up on login page

### ISSUE THREAD

**Issue by bemug** [tonyguolei/projet_dac#45]
When you access the login page, some elements (such as the navbar and buttons) seem to grow on page refresh.
It seems to be a bug in the CSS or/and JS.

This only seems to appear in Firefox.

**Comment by posva** [comment]
:-1:

**Comment by Iheve** [comment]
We think that is a firefox bug...

**Comment by bemug** [comment]
It sounds like a bootstrap theme bug.
