### ISSUE TITLE
Notification isn't triggered when somebody fund

### ISSUE THREAD

**Issue by tonyguolei** [tonyguolei/projet_dac#53]
The notification isn't triggered when somebody fund. But when the project reach seuil, it notifies that your project is funded.

**Comment by Jojolejobar** [comment]
We don't send a notification, each time someone fund a project, it's perfectly normal. If we do that, the owner will receive too many notifications.

**Comment by tonyguolei** [comment]
But when the project reach seuil, I receive 2 notifications. One is "your
project is founded", another is "your project reach seuil". Is that normal
we receive the first one at this moment?
Le 23 janv. 2015 00:13, "Guillaume Perrin" <notifications@github.com> a
écrit :

**Comment by Jojolejobar** [comment]
Typically, if a project you have funded reaches its goal you will receive a notification (It's a win, a project you have funded has reached its goal !), and if a project you created reaches its goal you will receive a notification (It's a win, your project has been funded !). So if your are the owner and you back the project you created, you will receive these two notifications

**Comment by tonyguolei** [comment]
Ok. It's clear. Thanks:)
Le 23 janv. 2015 00:24, "Guillaume Perrin" <notifications@github.com> a
écrit :
